### ISSUE TITLE
MVP #1: Alarm Clock

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#105]
We need to come up with some use examples of Simple IoT. Although SIOT has been used in several IoT systems, just pieces of it have been used and we are lacking complete examples. These MVP issues are used to brainstorm the feature, and keep track of enhancements needed to implement the idea.

So, MVP #1 ... it would be nice to have a reliable, highly configurable alarm clock without having to keep a phone in your bed room. Though most people simply use their phone, there might be reasons you don't want to use a phone as an alarm clock:

1) you want space/time away from your phone
2) you want your kids to have space/time away from their phone
3) you want a better alarm clock
4) you want a more powerful alarm clock (vibrate bed, etc)

Alarm clocks last about a year here (kids are hard on them and they only take so many falls to the floor), so seems this is a prime opportunity to build something that lasts and is high quality.

The idea is you can configure rules for various alarms in a web UI, and then use a local button/switch to enable/disable the alarm.

Features needed:

* [x] - get rules working again
* [x] - support for Shelly devices #189 
* [x] - get schedules conditions working again #547 
* [x] - support date in rule conditions #234
* [ ] - DST support #574 
* [ ] - GPIO support #129 
* [ ] - enclosure/mechanical design (may be wood, or 3d printed case)
* [ ] - document case study

**Comment by cbrake** [comment]
@collinbrake FYI

**Comment by cbrake** [comment]
I've been experimenting with using Shelly bulbs as an alarm clock, and I really like the experience -- much better than the jarring alarm that you have to find and turn off, so thinking this might another skew of this.

**Comment by cbrake** [comment]
our first MVP is complete!
